### ISSUE TITLE
Problem with SSL connection

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/postgresql-component#2]
A client is trying to connect with PostgreSQL DB set on Heroku. During `verifyCredentials` stage it complains that `error: no pg_hba.conf entry for host "85.184.250.161"`

Here is the whole log:
```js
Starting your Docker container ...
Starting application in apprunner
Starting slug download ...
Successfully downloaded and extracted slug file
Writing config vars to .profile.d/config_vars
Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
Recommending WEB_CONCURRENCY=1
Starting the application with node ./node_modules/elasticio-sailor-nodejs/runService.js verifyCredentials
Credentials passed for verification {"conString":"postgres://u3r2hhpnkscaeg:pb56d2e792a8330f196a6b335bb6715f290ddb9dea908149add8a33084593ccdc@ec2-34-225-114-75.compute-1.amazonaws.com:5432/d213t7cegk576j"}
error fetching client from pool { error: no pg_hba.conf entry for host "85.184.250.161", user "u3r2hhpnkscaeg", database "d213t7cegk576j", SSL off
at Connection.parseE (/app/node_modules/pg/lib/connection.js:539:11)
at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:366:17)
at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:105:22)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (_stream_readable.js:134:10)
at TCP.onread (net.js:548:20)
name: 'error',
severity: 'FATAL',
length: 168,
hint: undefined,
[INFO  tini (1)] Spawned child process '/runner/init' with pid '7'
detail: undefined,
position: undefined,
code: '28000',
internalPosition: undefined,
internalQuery: undefined,
schema: undefined,
[INFO  tini (1)] Main child exited normally (with status '0')
where: undefined,
constraint: undefined,
column: undefined,
table: undefined,
dataType: undefined,
file: 'auth.c',
routine: 'ClientAuthentication' }
line: '489',
Starting application in apprunner
Starting slug download ...
Successfully downloaded and extracted slug file
Writing config vars to .profile.d/config_vars
Recommending WEB_CONCURRENCY=1
Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
Starting the application with node ./node_modules/elasticio-sailor-nodejs/runService.js verifyCredentials
[INFO  tini (1)] Spawned child process '/runner/init' with pid '7'
[INFO  tini (1)] Main child exited with signal (with signal 'Terminated')
Tigran Khanzadyan
Dashboard
Organization Members
Developers
Settings
Tenant
×
 Acme Org
 
Settings
 
Security credentials
 
PostgreSQL
PostgreSQL
3 Linked PostgreSQL Accounts
Add New Account
 Verify Cancel test
Choose Agent
No Agent Selected
Error: Execution timeout. Please see logs for details.
Name Your Account *

test
 
Connection String *

postgres://u3r2hhpnkscaeg:pb56d2e792a8330f196a6b335bb6715f290ddb9dea908149add8a33084593ccdc@ec2-34-225-114-75.compute-1.amazonaws.com:5432/d213t7cegk576j
 Edit Delete My PostgreSQL account  latest
 Edit Delete Pet Store  latest
```

**Comment by khanzadyan** [comment]
@zubairov could it be that there is some setup needs to be done on Heroku side? Or maybe our component needs some `LOVE`?

**Comment by jhorbulyk** [comment]
It looks like PostgreSQL has a whitelist on the sever side and that they need to add an entry for our IP address: https://www.postgresql.org/docs/9.3/static/auth-pg-hba-conf.html

**Comment by zubairov** [comment]
@khanzadyan could you please follow-up with the customer as it's seems like an issue on their side and not on ours

**Comment by khanzadyan** [comment]
@zubairov the client is notified already. Thanks, @jhorbulyk for your investigation. I propose we add this information to the Readme.
